DROP TRIGGER IF EXISTS ArticleSetTimestamp ON ARTICLES.ARTICLE;

DROP TABLE IF EXISTS ARTICLES.ARTICLE;

DROP FUNCTION IF EXISTS  ARTICLES.Trigger_SetTimestamp;

DROP FUNCTION IF EXISTS ARTICLES.ARRAY_DISTINCT;

DROP FUNCTION IF EXISTS ARTICLES.ARRAY_DISTINCT_MINUS;

DROP SCHEMA IF EXISTS ARTICLES;

DROP INDEX CONCURRENTLY IF EXISTS articles_tag_dex;